# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - GroupMeBot

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production' # Ensure this environment is configured in your GitHub repo settings if needed
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5 # Using a more recent version of setup-python
        with:
          python-version: '3.11' # Matches your app's requirement

      # No need to create venv, install dependencies, or zip manually here.
      # Azure will handle this using requirements.txt due to SCM_DO_BUILD_DURING_DEPLOYMENT=true.
      # If you had linters or tests, you would run them here, potentially after installing
      # dependencies in a temporary venv for the CI runner only.

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'GroupMeBot' # Make sure this is your exact Azure App Service name
          slot-name: 'Production' # Or your specific deployment slot
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D8E58A713C5C4A90853D587F1978C0C6 }} # Your deployment secret
          package: . # This tells the action to deploy the content of the current directory (your repo root)
                     # Azure will then find app.py and requirements.txt.
